version: '3.8'

services:
  vnc_server:
    build: .
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    ports:
      - "5901:5901"
    environment:
      - DISPLAY=:1
      - VNC_RESOLUTION=${VNC_RESOLUTION:-1280x720}
    command: ["/start.sh"]
